[build]
  publish = "site"

# Catch-all redirect for SPA routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Explicit 404 rule (Netlify will use this when nothing matches)
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
