[build]
  publish = "site"

# First try to serve 404.html if nothing exists
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# (Optional) Only add this if you need SPA-style fallback
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
